/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

import { CrossMarginPrimeXMPosition } from './CrossMarginPrimeXMPosition';
import { PrimeXMMarginRequirementBreakdown } from './PrimeXMMarginRequirementBreakdown';
import { PrimeXMOffsetCreditBreakdown } from './PrimeXMOffsetCreditBreakdown';

/**
 * Groups XM margin requirement components, offset credits, and per-asset rows.
 */
export type CrossMarginPrimeRiskNettingInfo = {
  /**
   * Derivatives Clearing Organization Margin Requirement (DMR) is the margin requirement for all futures positions, derived from the Derivatives Clearing Organization model
   */
  dcoMarginRequirement?: string;
  /**
   * Portfolio Margin Requirement (PMR) is the margin requirement for all spot positions, derived from the XM model
   */
  portfolioMarginRequirement?: string;
  /**
   * Integrated Portfolio Margin Requirement (IPMR) is the margin requirement for all spot positions + futures positions with underlying assets eligible in Portfolio Margin.
   */
  integratedPortfolioMarginRequirement?: string;
  /**
   * Ineligible Futures Margin Requirement (IFMR) is the margin requirement for IPMR-ineligible futures contracts
   */
  ineligibleFuturesMarginRequirement?: string;
  pmrBreakdown?: PrimeXMMarginRequirementBreakdown;
  ipmrBreakdown?: PrimeXMMarginRequirementBreakdown;
  portfolioMarginOffsetCreditBreakdown?: PrimeXMOffsetCreditBreakdown;
  integratedPortfolioMarginOffsetCreditBreakdown?: PrimeXMOffsetCreditBreakdown;
  /**
   * Netted positions used in the model calculation.
   */
  xmPositions?: Array<CrossMarginPrimeXMPosition>;
};
