/**
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

import { ValidatorUnstakingInfo } from './ValidatorUnstakingInfo';

export type GetUnstakingStatusResponse = {
  /**
   * The portfolio ID
   */
  portfolioId: string;
  /**
   * The wallet ID
   */
  walletId: string;
  /**
   * The wallet address
   */
  walletAddress: string;
  /**
   * Current timestamp at time of API call
   */
  currentTimestamp: Date;
  /**
   * List of validators with unstaking information for this wallet
   */
  validators: Array<ValidatorUnstakingInfo>;
};
