/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export type MarketData = {
  /**
   * Base asset symbol (e.g., BTC, ETH, SOL)
   */
  symbol?: string;
  /**
   * Daily historical volatility over trailing 5 days (decimal, e.g., 0.65 = 65%)
   */
  vol5d?: string;
  /**
   * Daily historical volatility over trailing 30 days (decimal, e.g., 0.65 = 65%)
   */
  vol30d?: string;
  /**
   * Daily historical volatility over trailing 90 days (decimal, e.g., 0.65 = 65%)
   */
  vol90d?: string;
  /**
   * Average daily trading volume over trailing 30 days (USD)
   */
  adv30d?: string;
  /**
   * Weighted blend of the most recent vol_5d and the max vol_5d over last 30 days into a single volatility measure (decimal).
   */
  weightedVol?: string;
};
