/**
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

import { EstimateType } from './enums/EstimateType';
import { UnstakeType } from './enums/UnstakeType';

export type UnstakingStatus = {
  /**
   * Amount being unstaked (whole amount, e.g., 16 ETH)
   */
  amount: string;
  unstakeType?: UnstakeType;
  /**
   * Estimated date when unstaking will complete (ISO 8601 format)
   */
  finishingAt?: Date;
  /**
   * Estimated hours until this unstaking request completes
   */
  remainingHours?: number;
  /**
   * Timestamp when the unstake request was originally created
   */
  requestedAt?: Date;
  estimateType: EstimateType;
  /**
   * Detailed explanation of the estimate status for display to users.
   */
  estimateDescription: string;
};
