/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

/**
 * ValidatorAllocation specifies the validator and amount for staking or unstaking. Used for granular ETH V2 validator-level staking or unstaking operations.
 */
export type ValidatorAllocation = {
  /**
   * The validator address for performing staking operations
   */
  validatorAddress: string;
  /**
   * Amount for performing staking operations with this validator
   */
  amount: string;
};
