/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

/**
 * ValidatorUnstakePreview contains the per-validator breakdown for an unstake preview.
 */
export type ValidatorUnstakePreview = {
  /**
   * Public address of the validator being unstaked from
   */
  validatorAddress?: string;
  /**
   * Estimated amount that would be unstaked from this validator (in ETH)
   */
  estimatedUnstakingAmount?: string;
  /**
   * Estimated time until this validator\'s unstake completes, in hours
   */
  unstakeTimeEstimateInHours?: number;
  /**
   * Estimated date when this validator\'s unstake will complete (ISO 8601)
   */
  estimatedUnstakeDate?: string;
};
