/**
 * Copyright 2025-present Coinbase Global, Inc.
 *
 * This file is generated by Openapi Generator https://github.com/openapitools/openapi-generator
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *  Do not edit the class manually.
 */

export enum ActivityType {
  Unknown = 'ACTIVITY_TYPE_UNKNOWN',
  GovernanceVote = 'ACTIVITY_TYPE_GOVERNANCE_VOTE',
  Invitation = 'ACTIVITY_TYPE_INVITATION',
  WalletChange = 'ACTIVITY_TYPE_WALLET_CHANGE',
  ApiKeyChange = 'ACTIVITY_TYPE_API_KEY_CHANGE',
  SettingsChange = 'ACTIVITY_TYPE_SETTINGS_CHANGE',
  BillingPreferenceChange = 'ACTIVITY_TYPE_BILLING_PREFERENCE_CHANGE',
  PaymentMethodChange = 'ACTIVITY_TYPE_PAYMENT_METHOD_CHANGE',
  Withdrawal = 'ACTIVITY_TYPE_WITHDRAWAL',
  Deposit = 'ACTIVITY_TYPE_DEPOSIT',
  CreateWallet = 'ACTIVITY_TYPE_CREATE_WALLET',
  RemoveWallet = 'ACTIVITY_TYPE_REMOVE_WALLET',
  UpdateWallet = 'ACTIVITY_TYPE_UPDATE_WALLET',
  CastVote = 'ACTIVITY_TYPE_CAST_VOTE',
  EnableVoting = 'ACTIVITY_TYPE_ENABLE_VOTING',
  Stake = 'ACTIVITY_TYPE_STAKE',
  Unstake = 'ACTIVITY_TYPE_UNSTAKE',
  ChangeValidator = 'ACTIVITY_TYPE_CHANGE_VALIDATOR',
  Restake = 'ACTIVITY_TYPE_RESTAKE',
  AddressBook = 'ACTIVITY_TYPE_ADDRESS_BOOK',
  TeamMembers = 'ACTIVITY_TYPE_TEAM_MEMBERS',
  Billing = 'ACTIVITY_TYPE_BILLING',
  Security = 'ACTIVITY_TYPE_SECURITY',
  Api = 'ACTIVITY_TYPE_API',
  Settings = 'ACTIVITY_TYPE_SETTINGS',
  SmartContract = 'ACTIVITY_TYPE_SMART_CONTRACT',
  UserChangeRequestNoPas = 'ACTIVITY_TYPE_USER_CHANGE_REQUEST_NO_PAS',
  Web3Transaction = 'ACTIVITY_TYPE_WEB3_TRANSACTION',
  Web3Message = 'ACTIVITY_TYPE_WEB3_MESSAGE',
  ClaimRewards = 'ACTIVITY_TYPE_CLAIM_REWARDS',
}
